server:
  port: 9201

spring:
  application:
    name: api-service
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k9c201.p.ssafy.io:3306/itda_api?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: itda1235!@#%

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  data:
    redis:
      password: itda1235!@#%
      port: '6379'
      host: k9c201.p.ssafy.io

    mongodb:
      host: k9c201.p.ssafy.io
      port: 27017
      authentication-database: admin
      username: 'itda'
      password: 'itda1235!@#%'
      database: itda

logging:
  level:
    org.hibernate.SQL: debug
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE