spring:
  config:
    activate:
      on-profile: local

eureka:
  instance:
    hostname: 127.0.0.1

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

kafka-topic : api-status-changed-local