spring:
  config:
    activate:
      on-profile: local

eureka:
  instance:
    hostname: 127.0.0.1

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpExchanges, busRefresh, prometheus, metrics

kafka-topic: usage-register-topic-local